[package]
name = "notify_sound"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.32"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["full"] }
zbus = "5.13.2"
